if (!require("readxl")) install.packages("readxl")
library(readxl)

if (!require("readr")) install.packages("readr")
library(readr)

if (!require("dplyr")) install.packages("dplyr")
library(dplyr)

taiwan_env <- base::new.env()

taiwan_env$fdi_case_study <- readr::read_csv("data/FDI Case Study.csv", show_col_types = FALSE, n_max = 84 - 15)
glimpse(taiwan_env$fdi_case_study)
taiwan_env$salary <- readr::read_csv("data/Salary.csv", show_col_types = FALSE)
glimpse(taiwan_env$salary)
vd(taiwan_env$salary)
taiwan_env$residence_data <- readr::read_csv("data/Residence Data.csv", show_col_types = FALSE)
glimpse(taiwan_env$residence_data)
taiwan_env$twii <- readr::read_csv("data/TWII.csv", show_col_types = FALSE)
glimpse(taiwan_env$twii)
taiwan_env$asia_trade <- readr::read_csv("data/Asia Import Export Trade Data.csv", show_col_types = FALSE)
glimpse(taiwan_env$asia_trade)
taiwan_env$corporate_actions <- readxl::read_excel("data/Corporate Actions Market Data Taiwan.xlsx")
glimpse(taiwan_env$corporate_actions)
taiwan_env$cpi_taiwan <- readr::read_csv("data/CPI Taiwan 2001 - 2020.csv", show_col_types = FALSE)
glimpse(taiwan_env$cpi_taiwan)
taiwan_env$democracy_index <- readr::read_csv("data/democracy-index-eiu.csv", show_col_types = FALSE)
glimpse(taiwan_env$democracy_index)
taiwan_env$fdi_innovation <- readxl::read_excel("data/FDI and Innovation data.xlsx")
glimpse(taiwan_env$fdi_innovation)
taiwan_env$gdp_taiwan <- readr::read_csv("data/GDP Taiwan 2001 - 2020.csv", show_col_types = FALSE)
glimpse(taiwan_env$gdp_taiwan)
taiwan_env$trade_asia2 <- readr::read_csv("data/ImportExport Trade data Asia.csv", show_col_types = FALSE)
glimpse(taiwan_env$trade_asia2)
taiwan_env$taiwan_stock_index <- readxl::read_excel("data/Taiwan Capitalization Weighted Stock Index 2009 - 2021.xls")
glimpse(taiwan_env$taiwan_stock_index)
taiwan_env$tsm_stock <- readr::read_csv("data/TSM_1997-10-08_2025-04-22.csv", show_col_types = FALSE)
glimpse(taiwan_env$tsm_stock)

base::save(envir = taiwan_env, list = base::ls(envir = taiwan_env), file = "output/taiwan_env.RData")
